import { db } from './index';
import {
  BusinessType,
  Product,
  Category,
  Customer,
  Supplier,
  Sale,
  CartItem,
  LedgerTransaction,
  InventoryMovement,
  MarketingTemplate,
} from '@/types';

export interface DemoSeedResult {
  categoriesCount: number;
  productsCount: number;
  customersCount: number;
  suppliersCount: number;
  salesCount: number;
  ledgerCount: number;
  movementsCount: number;
}

export async function seedComprehensiveDemoData(
  targetBusinessId?: string,
  clearExisting = false
): Promise<DemoSeedResult> {
  const business = targetBusinessId
    ? await db.businesses.get(targetBusinessId)
    : await db.businesses.toCollection().first();

  if (!business) {
    throw new Error('No business found to seed data for.');
  }

  const businessId = business.id;
  const now = new Date();
  const nowIso = now.toISOString();

  if (clearExisting) {
    await db.categories.where('business_id').equals(businessId).delete();
    await db.products.where('business_id').equals(businessId).delete();
    await db.customers.where('business_id').equals(businessId).delete();
    await db.suppliers.where('business_id').equals(businessId).delete();
    await db.sales.where('business_id').equals(businessId).delete();
    await db.ledger_transactions.where('business_id').equals(businessId).delete();
    await db.inventory_movements.where('business_id').equals(businessId).delete();
  }

  // 1. Categories
  const categoryDefs = [
    { id: `cat_${businessId}_grains`, name: 'Grains & Atta (अनाज/आटा)', icon: 'wheat' },
    { id: `cat_${businessId}_dairy`, name: 'Dairy & Milk (डेयरी)', icon: 'milk' },
    { id: `cat_${businessId}_oils`, name: 'Edible Oils & Ghee (तेल/घी)', icon: 'droplet' },
    { id: `cat_${businessId}_snacks`, name: 'Snacks & Biscuits (नाश्ता/बिस्कुट)', icon: 'cookie' },
    { id: `cat_${businessId}_beverages`, name: 'Beverages & Tea (चाय/पेय)', icon: 'coffee' },
    { id: `cat_${businessId}_spices`, name: 'Spices & Masala (मसाले)', icon: 'sparkles' },
    { id: `cat_${businessId}_personal`, name: 'Personal Care & Soaps (साबुन)', icon: 'sparkles' },
    { id: `cat_${businessId}_cleaning`, name: 'Cleaning & Detergents (सफाई)', icon: 'spray' },
  ];

  for (const cat of categoryDefs) {
    await db.categories.put({
      id: cat.id,
      business_id: businessId,
      name: cat.name,
      icon: cat.icon,
      created_at: nowIso,
    });
  }

  // 2. 55+ Products Definitions
  const rawProducts: Array<Omit<Product, 'id' | 'business_id' | 'created_at' | 'updated_at' | 'sync_status'>> = [
    // Grains & Atta
    {
      name: 'Aashirvaad Shudh Chakki Atta 5kg',
      barcode: '890103000001',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 24500, // ₹245.00
      purchase_price: 21500,
      mrp: 26000,
      unit: 'packet',
      current_stock: 45,
      min_stock_level: 10,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '1101',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Fortune Chakki Fresh Atta 10kg',
      barcode: '890103000011',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 46000, // ₹460.00
      purchase_price: 41000,
      mrp: 49500,
      unit: 'packet',
      current_stock: 30,
      min_stock_level: 8,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '1101',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Tata Salt Vacuum Evaporated 1kg',
      barcode: '890103000004',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 2800,
      purchase_price: 2300,
      mrp: 3000,
      unit: 'packet',
      current_stock: 120,
      min_stock_level: 25,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '2501',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'India Gate Basmati Rice Feast Rozana 5kg',
      barcode: '890103000012',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 42000,
      purchase_price: 37000,
      mrp: 47500,
      unit: 'packet',
      current_stock: 22,
      min_stock_level: 5,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '1006',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Daawat Rozana Gold Basmati Rice 1kg',
      barcode: '890103000013',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 9500,
      purchase_price: 8200,
      mrp: 11000,
      unit: 'packet',
      current_stock: 50,
      min_stock_level: 10,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '1006',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Premium Toor Dal / Arhar Dal Desi 1kg',
      barcode: '890103000010',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 16500,
      purchase_price: 14500,
      mrp: 18000,
      unit: 'kg',
      current_stock: 110,
      min_stock_level: 20,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '0713',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Moong Dal Dhuli Super Clean 500g',
      barcode: '890103000014',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 7200,
      purchase_price: 6100,
      mrp: 8000,
      unit: 'packet',
      current_stock: 35,
      min_stock_level: 8,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '0713',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Chana Dal Polished 1kg',
      barcode: '890103000015',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 9800,
      purchase_price: 8400,
      mrp: 11000,
      unit: 'kg',
      current_stock: 80,
      min_stock_level: 15,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '0713',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Rajma Chitra Special 500g',
      barcode: '890103000016',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 8500,
      purchase_price: 7200,
      mrp: 9500,
      unit: 'packet',
      current_stock: 25,
      min_stock_level: 6,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '0713',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Kabuli Chana Dollar Big Size 1kg',
      barcode: '890103000017',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 15500,
      purchase_price: 13500,
      mrp: 17500,
      unit: 'kg',
      current_stock: 40,
      min_stock_level: 10,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '0713',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Sugar / Chini (Fine Crystal) 1kg',
      barcode: '890103000009',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 4400,
      purchase_price: 3800,
      mrp: 4800,
      unit: 'kg',
      current_stock: 200,
      min_stock_level: 40,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '1701',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Poha Thick (Flattened Rice) 500g',
      barcode: '890103000018',
      category_id: categoryDefs[0].id,
      category_name: 'Grains & Atta',
      selling_price: 3500,
      purchase_price: 2800,
      mrp: 4000,
      unit: 'packet',
      current_stock: 50,
      min_stock_level: 12,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '1904',
      is_active: true,
      is_favorite: false,
    },

    // Edible Oils & Ghee
    {
      name: 'Fortune Sunlite Sunflower Oil 1L Pouch',
      barcode: '890103000002',
      category_id: categoryDefs[2].id,
      category_name: 'Edible Oils & Ghee',
      selling_price: 13500,
      purchase_price: 12000,
      mrp: 15500,
      unit: 'packet',
      current_stock: 55,
      min_stock_level: 12,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '1512',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Dhara Kachi Ghani Mustard Oil 1L Bottle',
      barcode: '890103000019',
      category_id: categoryDefs[2].id,
      category_name: 'Edible Oils & Ghee',
      selling_price: 14500,
      purchase_price: 12800,
      mrp: 16500,
      unit: 'litre',
      current_stock: 35,
      min_stock_level: 8,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '1514',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Saffola Gold Pro Healthy Lifestyle Oil 1L Pouch',
      barcode: '890103000020',
      category_id: categoryDefs[2].id,
      category_name: 'Edible Oils & Ghee',
      selling_price: 17500,
      purchase_price: 15500,
      mrp: 19500,
      unit: 'packet',
      current_stock: 28,
      min_stock_level: 6,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '1512',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Amul Pure Cow Ghee 1L Tin',
      barcode: '890103000021',
      category_id: categoryDefs[2].id,
      category_name: 'Edible Oils & Ghee',
      selling_price: 61000, // ₹610.00
      purchase_price: 54000,
      mrp: 65000,
      unit: 'litre',
      current_stock: 18,
      min_stock_level: 4,
      tax_rate: 12,
      is_tax_inclusive: true,
      hsn_code: '0405',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Gowardhan Pure Cow Ghee 500ml Jar',
      barcode: '890103000022',
      category_id: categoryDefs[2].id,
      category_name: 'Edible Oils & Ghee',
      selling_price: 33000,
      purchase_price: 29500,
      mrp: 36000,
      unit: 'piece',
      current_stock: 20,
      min_stock_level: 5,
      tax_rate: 12,
      is_tax_inclusive: true,
      hsn_code: '0405',
      is_active: true,
      is_favorite: false,
    },

    // Dairy & Milk
    {
      name: 'Amul Taaza Homogenised Toned Milk 1L',
      barcode: '890103000003',
      category_id: categoryDefs[1].id,
      category_name: 'Dairy & Milk',
      selling_price: 7400,
      purchase_price: 6800,
      mrp: 7500,
      unit: 'packet',
      current_stock: 30,
      min_stock_level: 8,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '0401',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Amul Butter Pasteurised 500g Pack',
      barcode: '890103000023',
      category_id: categoryDefs[1].id,
      category_name: 'Dairy & Milk',
      selling_price: 27500,
      purchase_price: 25000,
      mrp: 28500,
      unit: 'piece',
      current_stock: 16,
      min_stock_level: 4,
      tax_rate: 12,
      is_tax_inclusive: true,
      hsn_code: '0405',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Amul Processed Cheese Slices 200g (10 Slices)',
      barcode: '890103000024',
      category_id: categoryDefs[1].id,
      category_name: 'Dairy & Milk',
      selling_price: 14500,
      purchase_price: 13000,
      mrp: 15500,
      unit: 'packet',
      current_stock: 12,
      min_stock_level: 3,
      tax_rate: 12,
      is_tax_inclusive: true,
      hsn_code: '0406',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Mother Dairy Fresh Paneer 200g',
      barcode: '890103000025',
      category_id: categoryDefs[1].id,
      category_name: 'Dairy & Milk',
      selling_price: 9000,
      purchase_price: 8000,
      mrp: 9500,
      unit: 'packet',
      current_stock: 14,
      min_stock_level: 4,
      tax_rate: 0,
      is_tax_inclusive: true,
      hsn_code: '0406',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Nestlé Everyday Dairy Whitener Milk Powder 400g',
      barcode: '890103000026',
      category_id: categoryDefs[1].id,
      category_name: 'Dairy & Milk',
      selling_price: 24000,
      purchase_price: 21200,
      mrp: 26000,
      unit: 'packet',
      current_stock: 22,
      min_stock_level: 5,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0402',
      is_active: true,
      is_favorite: false,
    },

    // Snacks & Biscuits
    {
      name: 'Parle-G Gold Biscuits 1kg Family Pack',
      barcode: '890103000005',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 11000,
      purchase_price: 9500,
      mrp: 12000,
      unit: 'packet',
      current_stock: 45,
      min_stock_level: 10,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '1905',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Britannia Good Day Cashew Cookies 600g',
      barcode: '890103000027',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 13000,
      purchase_price: 11200,
      mrp: 14500,
      unit: 'packet',
      current_stock: 35,
      min_stock_level: 8,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '1905',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Cadbury Oreo Original Vanilla Creme Biscuit 300g',
      barcode: '890103000028',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 9000,
      purchase_price: 7800,
      mrp: 10000,
      unit: 'packet',
      current_stock: 28,
      min_stock_level: 6,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '1905',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Maggi 2-Minute Masala Noodles 420g (Pack of 6)',
      barcode: '890103000006',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 8800,
      purchase_price: 7600,
      mrp: 9600,
      unit: 'packet',
      current_stock: 60,
      min_stock_level: 15,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '1902',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Sunfeast Dark Fantasy Choco Fills 300g',
      barcode: '890103000029',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 14000,
      purchase_price: 12000,
      mrp: 16000,
      unit: 'box',
      current_stock: 20,
      min_stock_level: 5,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '1905',
      is_active: true,
      is_favorite: false,
    },
    {
      name: "Lay's India's Magic Masala Potato Chips 50g",
      barcode: '890103000030',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 2000,
      purchase_price: 1650,
      mrp: 2000,
      unit: 'packet',
      current_stock: 80,
      min_stock_level: 20,
      tax_rate: 12,
      is_tax_inclusive: true,
      hsn_code: '2005',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Kurkure Masala Munch Crisps 90g',
      barcode: '890103000031',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 2000,
      purchase_price: 1650,
      mrp: 2000,
      unit: 'packet',
      current_stock: 75,
      min_stock_level: 20,
      tax_rate: 12,
      is_tax_inclusive: true,
      hsn_code: '1905',
      is_active: true,
      is_favorite: true,
    },
    {
      name: "Haldiram's Nagpur Bhelpuri Sev / Bhujia 400g",
      barcode: '890103000032',
      category_id: categoryDefs[3].id,
      category_name: 'Snacks & Biscuits',
      selling_price: 12500,
      purchase_price: 10800,
      mrp: 13500,
      unit: 'packet',
      current_stock: 30,
      min_stock_level: 8,
      tax_rate: 12,
      is_tax_inclusive: true,
      hsn_code: '2106',
      is_active: true,
      is_favorite: false,
    },

    // Beverages & Tea
    {
      name: 'Tata Tea Gold Leaf Tea 500g Pack',
      barcode: '890103000033',
      category_id: categoryDefs[4].id,
      category_name: 'Beverages & Tea',
      selling_price: 31000,
      purchase_price: 27500,
      mrp: 34000,
      unit: 'packet',
      current_stock: 32,
      min_stock_level: 6,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0902',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Brooke Bond Red Label Strong Tea 250g',
      barcode: '890103000034',
      category_id: categoryDefs[4].id,
      category_name: 'Beverages & Tea',
      selling_price: 14500,
      purchase_price: 12800,
      mrp: 16000,
      unit: 'packet',
      current_stock: 40,
      min_stock_level: 10,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0902',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Nescafé Classic Instant Coffee Jar 50g',
      barcode: '890103000035',
      category_id: categoryDefs[4].id,
      category_name: 'Beverages & Tea',
      selling_price: 18500,
      purchase_price: 16000,
      mrp: 20000,
      unit: 'piece',
      current_stock: 24,
      min_stock_level: 5,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '2101',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Bru Instant Coffee 100g Pouch',
      barcode: '890103000036',
      category_id: categoryDefs[4].id,
      category_name: 'Beverages & Tea',
      selling_price: 21000,
      purchase_price: 18500,
      mrp: 23000,
      unit: 'packet',
      current_stock: 18,
      min_stock_level: 4,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '2101',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Cadbury Bournvita Chocolate Nutrition Drink 500g Jar',
      barcode: '890103000037',
      category_id: categoryDefs[4].id,
      category_name: 'Beverages & Tea',
      selling_price: 24500,
      purchase_price: 21800,
      mrp: 26500,
      unit: 'piece',
      current_stock: 15,
      min_stock_level: 3,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '1806',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Coca-Cola Original Taste 750ml PET Bottle',
      barcode: '890103000038',
      category_id: categoryDefs[4].id,
      category_name: 'Beverages & Tea',
      selling_price: 4000,
      purchase_price: 3300,
      mrp: 4000,
      unit: 'piece',
      current_stock: 48,
      min_stock_level: 12,
      tax_rate: 28,
      is_tax_inclusive: true,
      hsn_code: '2202',
      is_active: true,
      is_favorite: true,
    },

    // Spices & Masala
    {
      name: 'MDH Deggi Mirch Powder 100g Pack',
      barcode: '890103000039',
      category_id: categoryDefs[5].id,
      category_name: 'Spices & Masala',
      selling_price: 9200,
      purchase_price: 8000,
      mrp: 9800,
      unit: 'box',
      current_stock: 36,
      min_stock_level: 8,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0904',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Everest Garam Masala 100g Carton',
      barcode: '890103000040',
      category_id: categoryDefs[5].id,
      category_name: 'Spices & Masala',
      selling_price: 8600,
      purchase_price: 7400,
      mrp: 9200,
      unit: 'box',
      current_stock: 30,
      min_stock_level: 6,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0910',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Catch Turmeric / Haldi Powder 200g Pouch',
      barcode: '890103000041',
      category_id: categoryDefs[5].id,
      category_name: 'Spices & Masala',
      selling_price: 6800,
      purchase_price: 5800,
      mrp: 7500,
      unit: 'packet',
      current_stock: 45,
      min_stock_level: 10,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0910',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Catch Coriander / Dhaniya Powder 200g Pouch',
      barcode: '890103000042',
      category_id: categoryDefs[5].id,
      category_name: 'Spices & Masala',
      selling_price: 6200,
      purchase_price: 5200,
      mrp: 7000,
      unit: 'packet',
      current_stock: 40,
      min_stock_level: 10,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0909',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Tata Sampann Kitchen King Masala 100g',
      barcode: '890103000043',
      category_id: categoryDefs[5].id,
      category_name: 'Spices & Masala',
      selling_price: 7800,
      purchase_price: 6600,
      mrp: 8500,
      unit: 'box',
      current_stock: 25,
      min_stock_level: 5,
      tax_rate: 5,
      is_tax_inclusive: true,
      hsn_code: '0910',
      is_active: true,
      is_favorite: false,
    },

    // Personal Care & Soaps
    {
      name: 'Dettol Original Soap 125g (Buy 3 Get 1 Free)',
      barcode: '890103000007',
      category_id: categoryDefs[6].id,
      category_name: 'Personal Care & Soaps',
      selling_price: 17500,
      purchase_price: 15000,
      mrp: 19500,
      unit: 'packet',
      current_stock: 22,
      min_stock_level: 5,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3401',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Dove Cream Beauty Bathing Bar 100g (Pack of 3)',
      barcode: '890103000044',
      category_id: categoryDefs[6].id,
      category_name: 'Personal Care & Soaps',
      selling_price: 18500,
      purchase_price: 16000,
      mrp: 21000,
      unit: 'packet',
      current_stock: 16,
      min_stock_level: 4,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3401',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Colgate Strong Teeth Toothpaste 200g Saver Pack',
      barcode: '890103000045',
      category_id: categoryDefs[6].id,
      category_name: 'Personal Care & Soaps',
      selling_price: 12000,
      purchase_price: 10200,
      mrp: 13500,
      unit: 'piece',
      current_stock: 35,
      min_stock_level: 8,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3306',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Head & Shoulders Anti-Dandruff Smooth Shampoo 180ml',
      barcode: '890103000046',
      category_id: categoryDefs[6].id,
      category_name: 'Personal Care & Soaps',
      selling_price: 17000,
      purchase_price: 14800,
      mrp: 19000,
      unit: 'piece',
      current_stock: 18,
      min_stock_level: 4,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3305',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Sensodyne Fresh Mint Sensitive Toothpaste 75g',
      barcode: '890103000047',
      category_id: categoryDefs[6].id,
      category_name: 'Personal Care & Soaps',
      selling_price: 14000,
      purchase_price: 12200,
      mrp: 15500,
      unit: 'piece',
      current_stock: 14,
      min_stock_level: 3,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3306',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Nivea Soft Light Moisturiser Cream 100ml',
      barcode: '890103000048',
      category_id: categoryDefs[6].id,
      category_name: 'Personal Care & Soaps',
      selling_price: 19900,
      purchase_price: 17200,
      mrp: 22500,
      unit: 'piece',
      current_stock: 12,
      min_stock_level: 3,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3304',
      is_active: true,
      is_favorite: false,
    },

    // Cleaning & Detergents
    {
      name: 'Surf Excel Quick Wash Detergent Powder 1kg',
      barcode: '890103000008',
      category_id: categoryDefs[7].id,
      category_name: 'Cleaning & Detergents',
      selling_price: 15500,
      purchase_price: 13500,
      mrp: 17000,
      unit: 'packet',
      current_stock: 35,
      min_stock_level: 8,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3402',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Ariel Matic Top Load Washing Powder 1kg',
      barcode: '890103000049',
      category_id: categoryDefs[7].id,
      category_name: 'Cleaning & Detergents',
      selling_price: 23000,
      purchase_price: 20200,
      mrp: 25500,
      unit: 'packet',
      current_stock: 24,
      min_stock_level: 5,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3402',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Vim Lemon Dishwash Gel Bottle 500ml',
      barcode: '890103000050',
      category_id: categoryDefs[7].id,
      category_name: 'Cleaning & Detergents',
      selling_price: 11500,
      purchase_price: 9800,
      mrp: 12500,
      unit: 'piece',
      current_stock: 40,
      min_stock_level: 10,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3402',
      is_active: true,
      is_favorite: true,
    },
    {
      name: 'Harpic Power Plus Original Toilet Cleaner 500ml',
      barcode: '890103000051',
      category_id: categoryDefs[7].id,
      category_name: 'Cleaning & Detergents',
      selling_price: 9500,
      purchase_price: 8200,
      mrp: 10500,
      unit: 'piece',
      current_stock: 32,
      min_stock_level: 6,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3402',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Lizol Disinfectant Surface & Floor Cleaner Citrus 500ml',
      barcode: '890103000052',
      category_id: categoryDefs[7].id,
      category_name: 'Cleaning & Detergents',
      selling_price: 11000,
      purchase_price: 9500,
      mrp: 12000,
      unit: 'piece',
      current_stock: 28,
      min_stock_level: 6,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3402',
      is_active: true,
      is_favorite: false,
    },
    {
      name: 'Colin Glass and Household Cleaner Spray 500ml',
      barcode: '890103000053',
      category_id: categoryDefs[7].id,
      category_name: 'Cleaning & Detergents',
      selling_price: 10500,
      purchase_price: 9000,
      mrp: 11500,
      unit: 'piece',
      current_stock: 20,
      min_stock_level: 4,
      tax_rate: 18,
      is_tax_inclusive: true,
      hsn_code: '3402',
      is_active: true,
      is_favorite: false,
    },
  ];

  const seededProducts: Product[] = [];
  for (let i = 0; i < rawProducts.length; i++) {
    const prodId = `prod_${businessId}_${i + 1}`;
    const productItem: Product = {
      ...rawProducts[i],
      id: prodId,
      business_id: businessId,
      created_at: nowIso,
      updated_at: nowIso,
      sync_status: 'synced',
    };
    await db.products.put(productItem);
    seededProducts.push(productItem);

    // Initial stock movement record
    await db.inventory_movements.put({
      id: `mov_init_${businessId}_${i + 1}`,
      business_id: businessId,
      product_id: prodId,
      product_name: productItem.name,
      movement_type: 'ADJUSTMENT',
      quantity: productItem.current_stock,
      previous_stock: 0,
      new_stock: productItem.current_stock,
      reason: 'Starter / Demo Inventory Setup',
      created_by: 'system',
      created_at: nowIso,
    });
  }

  // 3. 15 Diverse Customers with Udhar Khata balances
  const rawCustomers: Array<Omit<Customer, 'id' | 'business_id' | 'created_at' | 'updated_at' | 'sync_status'>> = [
    {
      name: 'Sunil Verma',
      phone: '9820123456',
      address: 'Flat 202, Gokuldham Society, Goregaon',
      customer_type: 'credit',
      opening_balance: 145000,
      current_balance: 145000, // ₹1,450.00 Udhar
      loyalty_points: 95,
      total_spent: 950000,
      total_visits: 16,
      last_visit_date: new Date(now.getTime() - 2 * 86400000).toISOString(),
    },
    {
      name: 'Pooja Patil',
      phone: '9819988776',
      address: 'Plot 15, Station Road, Dadar',
      customer_type: 'credit',
      opening_balance: 62000,
      current_balance: 62000, // ₹620.00 Udhar
      loyalty_points: 54,
      total_spent: 540000,
      total_visits: 9,
      last_visit_date: new Date(now.getTime() - 1 * 86400000).toISOString(),
    },
    {
      name: 'Rajesh Gupta',
      phone: '9833445566',
      address: 'Shanti Nagar, Lane 3, Andheri East',
      customer_type: 'vip',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 210,
      total_spent: 2100000,
      total_visits: 32,
      last_visit_date: nowIso,
    },
    {
      name: 'Priya Sundaram',
      phone: '9845012345',
      address: 'B-404, Palm Grove Apartments, Bandra',
      customer_type: 'credit',
      opening_balance: 280000,
      current_balance: 280000, // ₹2,800.00 Udhar
      loyalty_points: 120,
      total_spent: 1200000,
      total_visits: 19,
      last_visit_date: new Date(now.getTime() - 4 * 86400000).toISOString(),
    },
    {
      name: 'Vikram Malhotra',
      phone: '9811223344',
      address: 'Shop #8, Market Plaza, Malad',
      customer_type: 'credit',
      opening_balance: 95000,
      current_balance: 95000, // ₹950.00 Udhar
      loyalty_points: 68,
      total_spent: 680000,
      total_visits: 11,
      last_visit_date: new Date(now.getTime() - 3 * 86400000).toISOString(),
    },
    {
      name: 'Meena Tiwari',
      phone: '9876123450',
      address: 'A-12, Sai Kripa Chawl, Kurla',
      customer_type: 'regular',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 40,
      total_spent: 400000,
      total_visits: 7,
      last_visit_date: new Date(now.getTime() - 2 * 86400000).toISOString(),
    },
    {
      name: 'Suresh Yadav',
      phone: '9890123456',
      address: 'Near Hanuman Mandir, Borivali',
      customer_type: 'credit',
      opening_balance: 340000,
      current_balance: 340000, // ₹3,400.00 Udhar
      loyalty_points: 140,
      total_spent: 1400000,
      total_visits: 22,
      last_visit_date: new Date(now.getTime() - 5 * 86400000).toISOString(),
    },
    {
      name: 'Kavita Joshi',
      phone: '9823456789',
      address: 'C-301, Lake View Towers, Powai',
      customer_type: 'vip',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 310,
      total_spent: 3100000,
      total_visits: 45,
      last_visit_date: nowIso,
    },
    {
      name: 'Deepak Chauhan',
      phone: '9818765432',
      address: 'House #45, Shivaji Chowk, Chembur',
      customer_type: 'regular',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 32,
      total_spent: 320000,
      total_visits: 6,
      last_visit_date: new Date(now.getTime() - 6 * 86400000).toISOString(),
    },
    {
      name: 'Amit Singhania',
      phone: '9831234567',
      address: 'Row House 14, Royal Palms, Vikhroli',
      customer_type: 'credit',
      opening_balance: 120000,
      current_balance: 120000, // ₹1,200.00 Udhar
      loyalty_points: 88,
      total_spent: 880000,
      total_visits: 14,
      last_visit_date: new Date(now.getTime() - 4 * 86400000).toISOString(),
    },
    {
      name: 'Sunita Rao',
      phone: '9849012345',
      address: 'Block E, Teachers Colony, Santacruz',
      customer_type: 'regular',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 48,
      total_spent: 480000,
      total_visits: 8,
      last_visit_date: new Date(now.getTime() - 7 * 86400000).toISOString(),
    },
    {
      name: 'Manoj Kadam (Inactive 45 days)',
      phone: '9820987654',
      address: 'Near Old Bus Depot, Mulund',
      customer_type: 'inactive',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 15,
      total_spent: 150000,
      total_visits: 3,
      last_visit_date: new Date(now.getTime() - 45 * 86400000).toISOString(),
    },
    {
      name: 'Geeta Aggarwal',
      phone: '9810123456',
      address: 'Flat 601, Green Acres, Thane West',
      customer_type: 'vip',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 260,
      total_spent: 2600000,
      total_visits: 38,
      last_visit_date: nowIso,
    },
    {
      name: 'Naresh Bhai Kirana (Bulk / B2B)',
      phone: '9821001122',
      address: 'Shop 4, Wholesale Grain Market',
      customer_type: 'credit',
      opening_balance: 850000,
      current_balance: 850000, // ₹8,500.00 Udhar
      loyalty_points: 450,
      total_spent: 4500000,
      total_visits: 52,
      last_visit_date: new Date(now.getTime() - 1 * 86400000).toISOString(),
    },
    {
      name: 'Anil Deshmukh (Inactive 35 days)',
      phone: '9822334455',
      address: 'Near Old Post Office, Ghatkopar',
      customer_type: 'inactive',
      opening_balance: 0,
      current_balance: 0,
      loyalty_points: 31,
      total_spent: 310000,
      total_visits: 5,
      last_visit_date: new Date(now.getTime() - 35 * 86400000).toISOString(),
    },
  ];

  const seededCustomers: Customer[] = [];
  for (let c = 0; c < rawCustomers.length; c++) {
    const custId = `cust_${businessId}_${c + 1}`;
    const custItem: Customer = {
      ...rawCustomers[c],
      id: custId,
      business_id: businessId,
      created_at: nowIso,
      updated_at: nowIso,
      sync_status: 'synced',
    };
    await db.customers.put(custItem);
    seededCustomers.push(custItem);

    if (custItem.current_balance > 0) {
      await db.ledger_transactions.put({
        id: `ledg_init_${businessId}_${c + 1}`,
        business_id: businessId,
        party_type: 'customer',
        party_id: custId,
        party_name: custItem.name,
        transaction_type: 'CREDIT_SALE',
        amount: custItem.current_balance,
        balance_after: custItem.current_balance,
        notes: 'Initial Udhar Khata balance setup',
        created_at: custItem.last_visit_date || nowIso,
      });
    }
  }

  // 4. 6 Suppliers / Wholesalers
  const rawSuppliers: Array<Omit<Supplier, 'id' | 'business_id' | 'created_at' | 'updated_at' | 'sync_status'>> = [
    {
      name: 'Hindustan Unilever Distributor (HUL Agency)',
      phone: '9820011223',
      email: 'orders@huldummyagency.in',
      address: 'Godown 12, APMC Market, Vashi',
      gstin: '27AABCH1234A1Z1',
      opening_balance: 4500000,
      current_balance: 4500000, // ₹45,000 to pay
      notes: 'Weekly Tuesday supply for Soaps, Shampoos & Detergents',
    },
    {
      name: 'ITC Consumer Goods Wholesaler',
      phone: '9820022334',
      email: 'sales@itcwholesalerdummy.in',
      address: 'Plot 45, MIDC Industrial Area, Turbhe',
      gstin: '27AABCI5678B2Z2',
      opening_balance: 3200000,
      current_balance: 3200000, // ₹32,000
      notes: 'Supply Aashirvaad Atta, Sunfeast, Dark Fantasy & Bingo',
    },
    {
      name: 'Amul Dairy Supply Agency Mumbai',
      phone: '9820033445',
      email: 'amulsupply@dairydummy.in',
      address: 'Refrigerated Depot 8, Goregaon Milk Colony',
      gstin: '27AABCA9012C3Z3',
      opening_balance: 1500000,
      current_balance: 1500000, // ₹15,000
      notes: 'Daily early morning delivery for Milk, Butter, Cheese & Ghee',
    },
    {
      name: 'Nestlé India Regional Distribution',
      phone: '9820044556',
      email: 'orders@nestledummy.in',
      address: 'Central Logistics Park, Bhiwandi',
      gstin: '27AABCN3456D4Z4',
      opening_balance: 0,
      current_balance: 0,
      notes: 'Maggi, Nescafe & Everyday Milk Powder distributor',
    },
    {
      name: 'Local Agro Mandi Grain Trader',
      phone: '9820055667',
      address: 'Grain Merchant Yard, APMC Phase 2, Vashi',
      gstin: '27AABCZ7890E5Z5',
      opening_balance: 6000000,
      current_balance: 6000000, // ₹60,000
      notes: 'Bulk Dal, Rice, Sugar and Grain sacks supplier',
    },
    {
      name: 'Patanjali Ayurved & Herbal Agency',
      phone: '9820066778',
      address: 'Unit 5, Commercial Complex, Thane',
      gstin: '27AABCP1122F6Z6',
      opening_balance: 1800000,
      current_balance: 1800000, // ₹18,000
      notes: 'Herbal FMCG and ayurvedic wellness products',
    },
  ];

  for (let s = 0; s < rawSuppliers.length; s++) {
    const suppId = `supp_${businessId}_${s + 1}`;
    await db.suppliers.put({
      ...rawSuppliers[s],
      id: suppId,
      business_id: businessId,
      created_at: nowIso,
      updated_at: nowIso,
      sync_status: 'synced',
    });

    if (rawSuppliers[s].current_balance > 0) {
      await db.ledger_transactions.put({
        id: `ledg_supp_${businessId}_${s + 1}`,
        business_id: businessId,
        party_type: 'supplier',
        party_id: suppId,
        party_name: rawSuppliers[s].name,
        transaction_type: 'CREDIT_PURCHASE',
        amount: rawSuppliers[s].current_balance,
        balance_after: rawSuppliers[s].current_balance,
        notes: 'Initial Supplier balance setup',
        created_at: nowIso,
      });
    }
  }

  // 5. 20 Recent Sales / Invoices across today and the past 7 days
  const seededSales: Sale[] = [];
  const paymentMethods: Array<'cash' | 'upi' | 'credit'> = ['cash', 'upi', 'credit', 'cash', 'upi'];

  for (let s = 1; s <= 20; s++) {
    const daysAgo = Math.floor((s - 1) / 3);
    const saleDate = new Date(now.getTime() - daysAgo * 86400000 - (s % 3) * 3600000 * 2);
    const saleDateIso = saleDate.toISOString();

    const customer = seededCustomers[(s - 1) % seededCustomers.length];
    const pMethod = paymentMethods[(s - 1) % paymentMethods.length];

    // Pick 2-4 random items
    const numItems = 2 + (s % 3);
    const items: CartItem[] = [];
    let subtotal = 0;
    let taxTotal = 0;

    for (let it = 0; it < numItems; it++) {
      const prod = seededProducts[(s * 3 + it) % seededProducts.length];
      const qty = 1 + (it % 2);
      const unitPrice = prod.selling_price;
      const lineTotal = unitPrice * qty;
      const lineTax = Math.round((lineTotal * prod.tax_rate) / 100);

      subtotal += lineTotal;
      taxTotal += lineTax;

      items.push({
        product_id: prod.id,
        product_name: prod.name,
        quantity: qty,
        unit: prod.unit,
        unit_price: unitPrice,
        mrp: prod.mrp,
        discount_amount: 0,
        tax_rate: prod.tax_rate,
        tax_amount: lineTax,
        total_amount: lineTotal,
      });
    }

    const grandTotal = subtotal;
    const isCredit = pMethod === 'credit';
    const amountReceived = isCredit ? 0 : grandTotal;
    const balanceDue = isCredit ? grandTotal : 0;

    const saleId = `sale_${businessId}_${s}`;
    const invoiceNum = `INV-${1000 + s}`;

    const saleRecord: Sale = {
      id: saleId,
      business_id: businessId,
      invoice_number: invoiceNum,
      customer_id: customer.id,
      customer_name: customer.name,
      customer_phone: customer.phone,
      items,
      subtotal,
      discount_total: 0,
      tax_total: taxTotal,
      grand_total: grandTotal,
      payment_method: pMethod,
      amount_received: amountReceived,
      balance_due: balanceDue,
      change_returned: 0,
      payment_status: isCredit ? 'unpaid' : 'paid',
      status: 'completed',
      created_by: 'Owner (Ramesh)',
      created_at: saleDateIso,
      updated_at: saleDateIso,
      sync_status: 'synced',
    };

    await db.sales.put(saleRecord);
    seededSales.push(saleRecord);

    // If credit sale, add customer ledger entry
    if (isCredit) {
      await db.ledger_transactions.put({
        id: `ledg_sale_${saleId}`,
        business_id: businessId,
        party_type: 'customer',
        party_id: customer.id,
        party_name: customer.name,
        transaction_type: 'CREDIT_SALE',
        amount: grandTotal,
        balance_after: customer.current_balance,
        reference_id: saleId,
        notes: `Credit Sale Invoice #${invoiceNum}`,
        created_at: saleDateIso,
      });
    }
  }

  // Update business next_invoice_number
  await db.businesses.update(businessId, {
    next_invoice_number: 1021,
    updated_at: nowIso,
  });

  const finalResult: DemoSeedResult = {
    categoriesCount: categoryDefs.length,
    productsCount: seededProducts.length,
    customersCount: seededCustomers.length,
    suppliersCount: rawSuppliers.length,
    salesCount: seededSales.length,
    ledgerCount: await db.ledger_transactions.where('business_id').equals(businessId).count(),
    movementsCount: await db.inventory_movements.where('business_id').equals(businessId).count(),
  };

  return finalResult;
}
